services:
  postgres:
    container_name: postgre_container
    image: postgres:14

    environment:
      POSTGRES_USER: lalit
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

    networks:
      - microservice-network

    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@gmail.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"

    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"

    networks:
      - microservice-network

    restart: unless-stopped

  discover-service:
    container_name: discover-service

    build:
      context: ./discover-service

    image: discover-service

    ports:
      - "8761:8761"

    networks:
      - microservice-network

    restart: unless-stopped

  user-service:
    container_name: user-service

    build:
      context: ./user

    image: user-service

    ports:
      - "8081:8081"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/userdb
      DB_USERNAME: lalit
      DB_PASSWORD: password
      EUREKA_URL: http://discover-service:8761/eureka

    depends_on:
      - postgres
      - discover-service

    networks:
      - microservice-network

    restart: unless-stopped

  product-service:
    container_name: product-service

    build:
      context: ./product

    image: product-service

    ports:
      - "8083:8083"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/productdb
      DB_USERNAME: lalit
      DB_PASSWORD: password
      EUREKA_URL: http://discover-service:8761/eureka

    depends_on:
      - postgres
      - discover-service

    networks:
      - microservice-network

    restart: unless-stopped

  order-service:
    container_name: order-service

    build:
      context: ./order

    image: order-service

    ports:
      - "8082:8082"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/orderdb
      DB_USERNAME: lalit
      DB_PASSWORD: password
      EUREKA_URL: http://discover-service:8761/eureka

    depends_on:
      - postgres
      - discover-service

    networks:
      - microservice-network

    restart: unless-stopped

  auth-service:
    container_name: auth-service

    build:
      context: ./auth

    image: auth-service

    ports:
      - "8084:8084"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/authdb
      DB_USERNAME: lalit
      DB_PASSWORD: password
      EUREKA_URL: http://discover-service:8761/eureka

    depends_on:
      - postgres
      - discover-service

    networks:
      - microservice-network

    restart: unless-stopped

  api-gateway:
    container_name: api-gateway

    build:
      context: ./api-gateway

    image: api-gateway

    ports:
      - "8080:8080"

    environment:
      EUREKA_URL: http://discover-service:8761/eureka

    depends_on:
      - discover-service

    networks:
      - microservice-network

    restart: unless-stopped

networks:
  microservice-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: