spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:

        # Swagger routes
        - id: auth-docs
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: user-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: product-docs
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: order-docs
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        # Normal API routes
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs

      - name: User Service
        url: /api/users/v3/api-docs

      - name: Product Service
        url: /api/products/v3/api-docs

      - name: Order Service
        url: /api/orders/v3/api-docs

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/